[package]
name = "RustyDocs"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = "0.27"
strum_macros = "0.27"
chrono = "0.4.39"
rand = "0.9"  
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"